### ISSUE TITLE
Duration of borrow wording

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#158]
### Context

Now we now that the duration of tx (borrow) depends if they are cross chain, or same chain.

In case of cross chain, a tx will take around 3 to 5 minutes
In case of same chain, a tx will take few blocks (less than a minute)

@brozorec can you confirm for the durations ?

### Todo

- [ ] Update wording in `Header > notification` after borrowing
- [ ] Update wording in `Borrow > estimated cost`
- [ ] Send a message to mark to make sure I don't forget anything
