### ISSUE TITLE
Update design of account modal

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#168]
After a discussion with mark, he changed the design a little. Update the frontend according to it. I think the [Mui Popover](https://mui.com/material-ui/react-popover/#main-content) component is a perfect fit for this case.

[> Design on Figma](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=2553%3A43486)

### Todo
- [x] Change the design
- [x] When the user click on the address, show the popover
- [x] Change the wording if there is no transaction
- [x] Fill the `Connected with {walletName}` (we forgot to do it previously)
- [ ] ~~Update responsive design ([Figma](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=2745%3A45281&t=Z0Fy0wHyKwy7b3j9-4))~~ moved to #188 

---
### Desktop: 
![image](https://user-images.githubusercontent.com/24778042/205864197-d24ab70d-7ac1-4152-bce4-c65182921f66.png)
---
### Mobile: 
<img width="818" alt="Capture d’écran 2022-12-13 à 10 00 39" src="https://user-images.githubusercontent.com/15159459/207273256-558d6376-491d-4424-9138-6f760bb40af7.png">
