### ISSUE TITLE
Borrow: Update sign & borrow flow

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#194]
### Context

We updated the design to have `approval` and `signing` step in a modal. This way we can handle errors better.

### Todo

- [x] Est. how long will it takes and all the tasks needed
- [x] When the user clicks on "sign and borrow" it should open a modal directly
- [x] Display "Sign permit" with a loader while waiting for the user to sign the transaction [> design](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=2905%3A58704&t=NvLej27HH9I1tCi5-1)
- [x] If the user cancels the signing, display an error [> design](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=2905%3A59665&t=NvLej27HH9I1tCi5-1)
- [x] Display the transaction loading modal while waiting for the user to confirm the transaction. [> design](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=2905%3A59333&t=NvLej27HH9I1tCi5-1)
- [x] If the user cancels the transaction, display "transaction rejected" [> design](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=2905%3A59665&t=aIoenYijiOZsRO5q-1)
- [x] Then display the pending transaction modal (no change needed here)
- [x] If the submitted tx fails, display error in the transaction modal

### Related

None atm

**Comment by doliG** [comment]
Not planned for January release

**Comment by brozorec** [comment]
We need to groom this ticket because some of the points may have already been addressed + change links to the new Figma.
