### ISSUE TITLE
Front-end Architecture

### ISSUE THREAD

**Issue by 0xdcota** [Fujicracy/fuji-v2#2]
Investigations:
- [x] Determine library for web3 connection
- [x] Determine app state -- How different components talked to each other, how do we maintain of what the user is doing so in the next page it is available for example
- [x] State of the transactions, how do we deal with this topic? In single blockchain we have several states of a transaction and going cross chain will require tracking those states on different blockchains.
- [x] Using GraphQL for querying Connext transaction status, mainly learn how it works in case it is needed.
- [x] How to query states from multiple chains at the same time, not relying only on the injected provider.
- [x] Typescript

---
**Todo**

Create an app in frontend with
- [x] Next.JS & TypeScript,
- [x] #37
- [x] Add xstate
- [x] #39
- [x] Add Onboard + basic onboarding and put user in react context
