### ISSUE TITLE
Markets: show error when defillama api fails

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#219]
### Context

To display all available markets, we use Defillama API. It's an alpha version and sometimes it fails, so we have to find a way to display a nice error. Waiting for the design.

### Todo

- [ ] If we cannot fetch defillama, the sdk should still return a list where apy apr and rewards are 0 or unset.
- [ ] Display unset value as ?? (tbd)
- [ ] In case the sdk fail, display ?? (tbd)

### Related

- issue related #155

**Comment by doliG** [comment]
@Markoyw FYI I created a task to handle the error state when defillama api fails, so you can mention me here when the design is ready :)

**Comment by doliG** [comment]
@brozorec says that these kind of errors should not happen because in case DefiLlam API fails then we don't have APY and APR and the rewards, but the rest should be available.

If the result is 0, then the frontend should display a "-" or "n/a" (@Markoyw which one do you think is better ?)

**Comment by Markoyw** [comment]
Hey @doliG 

Curious - are we able to display an error icon next to it? Just so that the user is aware that it's an error, attaching an EX below,

![image](https://user-images.githubusercontent.com/34123690/210826498-1949b9bf-e274-4f57-b6c1-bc400c95d6b3.png)

**Comment by brozorec** [comment]
done with #292
