### ISSUE TITLE
Onboarding Modal: Tutorial + Terms & Agreement

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#331]
### Context 

When the user visits the app for the first time, they need to be presented with some "how it works" content. They also need to accept the Terms & Agreement and be warned about the risks.

### Overview

- This task consists of creating two distinct elements: "Safety Notice" (SN) and "Walkthrough" (WT).
- To know if the user has accepted the terms and was walked through the onboarding, we need to save a JSON item in the LocalStorage.
- The LocalStorage item contains the date and time on which the terms were accepted and if they went through the onboarding.
- Designs are provided in #221 

### TODOs

- [x] Create a new shared component for both elements and add it to the app root.
- [x] Add new actions and properties to "auth.store" to read from and write to LocalStorage.
- [x] On load app, read from LocalStorage and check if json element is present. If it's present, skip.
- [x] The modal appears when the user visits the app for the first time and can't be closed if the user clicks outside.
- [x] On SN, the button is disabled if the user doesn't check the box.
- [x] When the user accepts the terms in the SN, save data to LocalStorage.
- [x] After the user accepts the terms on the SN, display the WT
- [x] If the user clicks on "Skip, I will explore on .." or reaches the last step of the onboarding, store data to LocalStorage and close the modal.
