### ISSUE TITLE
Borrow: Slippage settings

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#336]
### Context

This ticket is the last part of #242 

When the user does a cross-chain operation, there is a chance the user suffers some slippage. More info about it, can be found [here](https://github.com/Fujicracy/fuji-v2/issues/253) and [here](https://github.com/Fujicracy/fuji-v2/issues/196#issuecomment-1425646865). We have to provide the user with a way to control the slippage settings when they are about to make a cross-chain call.

Designs for this ticket are [here](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=3299%3A62382&t=l5bpYVqEF49M0CSG-1).

Slippage is expressed in BPS (basis points): one basis point is equivalent to 0.01%. If the user inputs 0.50%, you should send to the dedicated sdk methods the value 50. The default slippage is 0.30% or 30 BPS.

### TODOs
- [ ] Create a new shared component and integrate it both on the borrow page and the manage position page
- [ ] The modal pops up when the user clicks on the clog icon and closes when they click on close btn or outside
- [ ] There are 3 choices between which the user can select (1%, 0.5% and 0.3%). Each of these choices is a btn.
- [ ] Selected by default is 0.3%
- [ ] The 4th element is an input, when the user clicks on the btns the input gets pre-filled. 
- [ ] The user can set their own % in the input (max 100).
- [ ] Create a new prop in the borrow store that accounts for the slippage and update it accordingly after user's interaction.
- [ ] On calling one of the SDK previews methods in `fetchRoutes()` in "packages/frontend/helpers/borrow.ts" pass the slippage as the last input (check [here](https://github.com/Fujicracy/fuji-v2/blob/main/packages/sdk/src/Previews.ts))
