### ISSUE TITLE
Bumping fees with Defender

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#348]
### Context

This is the first part of #130

For a cross-chain tx through Connext, a relayer fee needs to get paid so that the tx gets executed on the destination chain.
More info about different types of Connext fees [here](https://docs.connext.network/developers/guides/estimating-fees). 

We want to sponsor this fee. That's why we decided to use OpenZeppelin Defender and set up the following flow for every chain:

1. A **Sentinel** listens for the `XCalled` event emitted by the "ConnextRouter".
2. When the event gets emitted, the sentinel fires up an **Autotask**. 
3. **Autotask** initiates a transaction through a **Relayer** that calls `ConnextRouter.bumpFee()` .

The relayer fees are different for every chain and depend on multiple factors. We need to estimate this fee and pass this data to `ConnextRouter.bumpFee()`. Fortunately, the connext sdk provides a method for it. The role of the **AutoTask** is to use the data from the `XCalled` event to determine the destination chain and to call the connext sdk ("@connext/sdk").

### Notes

- Defender doesn't allow the code size of an autotask to exceed 5 MB. However, we want to use "@connext/sdk" for the estimation of the relayer fee, and when we bundle it, we get to over 17 MB. A workaround we found was to deploy a cloud function that does that job and simply returns the necessary value to the autotask.
- Defender provides a way to manage all resources in a declarative way with ["defender-serverless"](https://github.com/OpenZeppelin/defender-serverless). It's a great option but it's still under active development and missing extensive documentation. Bumped into the following problem but got support and resolved it:
 https://forum.openzeppelin.com/t/event-ignored-in-a-sentinel-setup-with-serverless/34915

**Comment by brozorec** [comment]
### Todos

- [ ] add config for Gnosis
- [ ] add config for Arbitrum
- [ ] add config for Ethereum
- [ ] add config for BNB chain
- [ ] edit readme to explain how everything works
- [ ] add readme for the cloud function
- [ ] add husky for "package/defender"
