### ISSUE TITLE
Placeholder for the Lend page

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#371]
### Context
At the private launch, the lending vaults won't be available but we want to keep a reference to this feature. We have already implemented on the markets page a "Coming soon" tab for "Lending". However, clicking on the "Lend" section in the header leads to a 404 error. We want to add a similar placeholder for "/lend" as for the markets page.

### TODOs
- [x] simplify the placeholder component and comment out the connection and the email (keep only the image, the title and the message)
- [x] implement in `my-positions`, the exact same way
- [x] take the placeholder component from the markets page and bring it to the page "/lend"

![Image](https://user-images.githubusercontent.com/9572072/224763339-802308ab-460e-4136-8338-6bbe7e943ac0.png)

The text is not final and might be changed in the future.

**Comment by ferostar** [comment]
Hey @NikolaiYurchenko in case you didn't notice, just added another item to the task.
