### ISSUE TITLE
Tooltip with all lending providers

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#407]
### Context
A vault should be linked to multiple lending providers (Aave, Compound, etc.). On the borrow and manage-position page, we display the borrow and collateral interest rates only for the "active" provider, i.e. only the one to which the vault is currently linked. The user should be aware of what are the APR/APYs of the other lending providers.

### TODOs
- [x] reorder rows in Overview from
![image](https://user-images.githubusercontent.com/9572072/227906676-c3811a00-02a6-4884-bbca-f8d4b6909192.png)
to
![image](https://user-images.githubusercontent.com/9572072/227906790-f2baa695-39e1-49c3-a336-333a464ce4cd.png)
and remove redundant provider name
- [x] on hover of the row with the supply APY, display a tooltip with a list of all integrated providers and their respective supply APYs
- [x] on hover of the row with the borrow APR, display a tooltip with a list of all integrated providers and their respective borrow APRs

- The design for the tooltip can be found in ([Figma](https://www.figma.com/file/LkNVe5ob1LjGpbGU74Hcrs/Fuji---Design-Files-(DUP)?node-id=4835%3A79673&t=tdB7q6YKYrcqI8ox-1)).
- We are going to use the same tooltip for the vault's analytics component.
- The data about the linked providers to a particular vault and their interest rates can be found in `allProviders[vaultAddr]` property in "borrow.store".

### Future work
- Deprecate `LendingProviderDetails` and use `LendingProviderWithFinancials` where are available also the farming rewards.
