### ISSUE TITLE
Borrow: Manage open position

### ISSUE THREAD

**Issue by iafhurtado** [Fujicracy/fuji-v2#41]
**Meta**

Estimation Time: 5 days

[View design >](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=509%3A13304&t=hltTwUy1et3zT5gR-1)

**Todo**
- [ ] If vault balance is null, redirect user to borrow page
- [ ] If vault balance is not null, the form display a modal that redirect to the manage position page [> design](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=2957%3A46792&t=GMYcBLYH3XNVo9Et-1)
- [ ] I can see the icon (1) and on hover the text "Your position is currently on {name} network"
- [x] I cannot edit the token
- [ ] I can see a button add positon (2)
  - [ ] On click switch between "deposit and borrow" and "payback and withdraw" mode
- [ ] I can change the collateral amount
  - [ ] On change, the overview pane changes according to the design (3)
- [ ] I can change the debt amount
  - [ ] On change, the overview pane changes according to the design (4)
- [ ] The button is updated depending on debt and collateral, and if we are in "deposit and borrow" or "payback and withdraw" mode
- [ ] The user can either deposit || && borrow, repay || && withdraw (need to be better defined but in code it's the exact same call to sdk. What changes is how we display it.
- [ ] Actions pending display "1 pending" instead of the address (same as borrow)

**How to**
Retrieve balance of user in a vault ?
Use `BorrowingVault.getBalances(address)`. If balance is 0. then the user don't have position -> open position form
Else -> manage position form

**Others**
- Inconsistency in design: "Add collateral + Borrow => Deposit and borrow"
- Missing: what should we do on cross chain tx ? See @brozorec comment below for a full explanation.

**Comment by ferostar** [comment]
@brozorec Guillaume closed his [PR](https://github.com/Fujicracy/fuji-v2/pull/187) with the message `Cancelled and closed. Store refacto can be found on https://github.com/Fujicracy/fuji-v2/pull/280`. I guess the work was outdated and it wasn't worth continuing it. Meaning it needs to be done from scratch on a fresh component instead of separating `Borrow` into two.

**Comment by brozorec** [comment]
@ferostar yep, that's correct. As we said, he started implementing it on the same components as the borrow page but we wanted to separate them.

**Comment by ferostar** [comment]
After having a look at the Figma designs, and what I think it's doable in the screen, I completely agree with Guillaume's initial idea. Our `Borrow` component would cover both cases There will be big differences of course, but I'll try to abstract them as much as possible. And I will rename the `Borrow` component into `Position` and move it to the `/Shared` folder.

**Comment by ferostar** [comment]
@brozorec I'm sorry, but I remember you showing something about this in one of our first meetings. Checklist says ` I can see a button add positon` but I think you said something on that part should be gone (I'm guessing add position is just borrow and manage is just for editing an existing one, so nothing to 'add') but I could be completely mistaken.

**Comment by brozorec** [comment]
@ferostar maybe we talked about something else. 
"Add position" is for deposit and/or borrow, meaning we add up to the position, increasing the collateral and/or the debt. "Remove position" is for payback and/or withdraw.

**Comment by ferostar** [comment]
Makes all the sense in the world @brozorec . It was in our first meeting I think when we discussed the following steps, and I know you said something along those lines, but I can't remember what, and it's driving me crazy. Thanks for answering.

**Comment by brozorec** [comment]
> Makes all the sense in the world @brozorec . It was in our first meeting I think when we discussed the following steps, and I know you said something along those lines, but I can't remember what, and it's driving me crazy. Thanks for answering.

Wasn't it about the case that when the user is on the borrow page and they have already an open position in the selected vault, we want to redirect them to manage page?

**Comment by ferostar** [comment]
> > Makes all the sense in the world @brozorec . It was in our first meeting I think when we discussed the following steps, and I know you said something along those lines, but I can't remember what, and it's driving me crazy. Thanks for answering.
> 
> Wasn't it about the case that when the user is on the borrow page and they have already an open position in the selected vault, we want to redirect them to manage page?

That wasn't it, it was something related to a component. We'll remember it.

**Comment by DaigaroCota** [comment]
Adding here this screen shot of the intended design for quick  reference.

![Image](https://user-images.githubusercontent.com/32775237/221031959-8f5f4978-fada-4b0d-926d-4bbc05c081c4.png)
