### ISSUE TITLE
Transaction Confirmation

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#431]
### Context
After the user makes all inputs, we want to display a transaction summary.

Here're the designs: [link](https://www.figma.com/file/LkNVe5ob1LjGpbGU74Hcrs/Fuji---Design-Files-(DUP)?node-id=5129%3A71330&t=B71VEurTgR6vhpYE-1). Skipping some of the specs because we've already talked about them but if any question pops up, feel free to reach out.

### TODOs
- [ ] remove the modal with the warning about the close to max LTV and display the warning here
- [ ] display this modal before the signing step if there's such

Question: Do we display this modal after or before approval? @ferostar @NikolaiYurchenko

**Comment by NikolaiYurchenko** [comment]
https://github.com/Fujicracy/fuji-v2/pull/434

**Comment by NikolaiYurchenko** [comment]
@brozorec answer to question: after, because we can not estimate gas fees before approval

**Comment by ferostar** [comment]
- [ ] In the route cards, the line is bigger when there are icons, so it looks a bit poor
<img width="462" alt="Captura de pantalla 2023-04-05 a la(s) 15 37 20" src="https://user-images.githubusercontent.com/501915/230174389-7bc4ed21-6623-4dfa-b140-e4bf5aeeb0cf.png">

- [ ] `Borrow limit left` is always 0. Did an operation with an `LTV` of around `30%`, so it shouldn't be 0 at all. Also, there's already a `borrowLimit` function in the `assets` helper. While it has a bug atm, you can use it here. In this confirmation modal, the idea is to show how much could the user borrow. The "...left" part. So if the user is doing an operation with an LTV of 30%, it means they could borrow a lot more until getting the recommended value. That's what we want to show.
