### ISSUE TITLE
Manage Position - Title

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#432]
### Context
During the internal testing, there was some feedback that the manage page and the borrow page are too similar, creating confusion.

Here are the proposed designs [Figma >](https://www.figma.com/file/LkNVe5ob1LjGpbGU74Hcrs/Fuji---Design-Files-(DUP)?node-id=5131%3A76111&t=IzvsqrJwhbEXRqaS-1).

### TODOs
- [ ] change buttons "Add position" and "Remove position" to a toggle with "Deposit / Borrow" and "Payback / Withdraw"
- [ ] add navigation to "my-positions" page
- [ ] add a sub-header with the assets information; the title is dynamic. When the user is on "Deposit / Borrow", we display "Borrow" and "Collateral". When the user is on "Payback / Withdraw", we display "Payback" and "Collateral"
