### ISSUE TITLE
Enable 3-chain transactions

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#462]
### Context
We want to enable 3-chain transactions only when managing an open position. We disabled the chain selection for borrow and payback when managing because it introduced some complexity in how this form works. As we stabilized the code base, we can now enable those transactions.

Example: the user has an open WETH/USDC position on Optimism; they want to repay it with USDC from Arbitrum and withdraw the collateral to Polygon (Arbitrum -> Optimism -> Polygon):

Bridge USDC from Arbitrum to Optimism -> payback USDC and withdraw WETH from the vault on Arbitrim -> bridge WETH from Arbitrum to Polygon

### TODOs
- [ ] SDK - update previews
- [ ] UI - enable chain selection in manage page
- [ ] UI - we can have more than 3 steps in the confirmation modal
- [ ] UI - notifications: we need to check if the steps have 3 chains and do the polling of `getConnextTxDetails` twice, for the 1st cross-chain transaction and a 2nd one
- [ ] UI - steps in transaction modal to check if affected
- [ ] UI - transaction history to check if affected

**Comment by ferostar** [comment]
Hi @brozorec I was looking at the sdk functions and we're preventing the 3-chain operations with the following checks:

- `borrow`, `withdraw` and `outflowRoutingDetails`have

```
srcChainId !== vault.chainId && tokenOut.chainId === vault.chainId
```

- `depositAndBorrow`, `paybackAndWithdraw` and `depositAndBorrowRoutingDetails` have
```
srcChainId !== destChainId && destChainId === vault.chainId
```
- And `paybackAndWithdrawRoutingDetails` has
```
tokenIn.chainId !== tokenOut.chainId && tokenOut.chainId === vault.chainId
```

Not sure about the current status, if it's a matter of removing/updating the checks. We can have a call if you want me to give a hand with this one.

**Comment by brozorec** [comment]
hey @ferostar thanks for checking this out :pray: Yes, these are the places where we have to implement the 3-chain logic in the SDK. I already started writing it and will create a PR soon. The Previews have become a monster file and adding more code will worsen the situation. I will write the 3-chain logic but I'll appreciate your help in getting ideas to split and refactor this big chunk. 

So here's how I see this moving forward:
1. Add the 3-chain logic to the existing one, as it is, and make sure everything works.
2. Adapt the UI with the points above.
3. Refactor the Previews.

**Comment by ferostar** [comment]
> hey @ferostar thanks for checking this out 🙏 Yes, these are the places where we have to implement the 3-chain logic in the SDK. I already started writing it and will create a PR soon. The Previews have become a monster file and adding more code will worsen the situation. I will write the 3-chain logic but I'll appreciate your help in getting ideas to split and refactor this big chunk.
> 
> So here's how I see this moving forward:
> 
>     1. Add the 3-chain logic to the existing one, as it is, and make sure everything works.
> 
>     2. Adapt the UI with the points above.
> 
>     3. Refactor the Previews.

Sounds like a plan. We definitely need to do something with that file! I remember having a look while adding error handling, it is a monster indeed and a lot could be abstracted but it's not going to be easy. Looking forward to it 🎉
