### ISSUE TITLE
[Onboarding] Welcome chris

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#47]
Hello Chris, and welcome to Fuji 👋

I'm on vacation until Sept 25th, so here are instructions for your first week.

Objectives of this week are multiple:
- First to get acquitained with Fuji team and repositories. I recommend that you take part of daily meetings. Also feel free to send message to Daigaro (solidity dev), Ivan (product lead) and Mark (designer) to meet them around a coffee break.
- Then, start the implementation of the form ([design available here](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=155%3A2286)). The first step is to start [theming material UI](https://mui.com/material-ui/customization/theme-components/), in sync with Mark. We discussed building a design system but I'm not sure he already defined the components. If yes build it, if not go MVP and we'll built it later.

I'm available for you via What's App, and suggest a 15 to 30 minutes call every two days to check your blockers and answer your questions. If you need faster answer feel free to reach Boyan.

Best of luck,
yome

---
**Todo**
 - [x] Get access to discord (ask Boyan)
 - [x] Get access of FujiDAO tracks calendar (ask Boyan)
 - [x] Get access of Figma (ask Mark)
 - [x] Read #2 on Frontend architecture. Feel free to share your thoughts.
 - [x] Read this [documentation](https://cuboid-production-824.notion.site/Fuji-V2-Himalaya-70bdd796b355435b8ef958b136cc44fb) which is an overview of what we are trying to build. Don't worry if you don't understand everything at first. Note: this doc is still a draft.
 - [x] Check #31, it's an issue I use to have an overview of all the task in frontend and track progress
 - [x] Material UI theming
	 - [x] Button (variant with gradient and flat)
	 - [x] Container (variant with borders and not) - I used the [Mui Card component](https://mui.com/material-ui/react-card/) which offer variants
	 - [x] Select
	 - [x] Colors (primary, text, secondary)
	 - [x] Typography
 - [x] Borrow form integration 
 - [x] Header integration
