### ISSUE TITLE
Slippage

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#473]
### Context
The default slippage is currently set to 30 BPS (0.3%). In some cases, this turns out to be low, considering the available liquidity at Connext. The user is required to update the slippage from the ConnextScan UI manually and to wait way longer for their transaction to settle.

### TODOs
- [ ] change the default slippage to 0.5%
- [ ] keep the same options from which the user can select (1%, 0.5%, 0.3% and custom)
- [ ] When the user is on the confirmation modal, compare the selected slippage and the slippage returned from the SDK preview methods. If the returned slippage is higher than the selected one, display a warning message in the modal:
"Expected slippage for this transaction might be higher than your slippage tolerance. This may lead to a longer waiting time for your transaction to be executed on the destination chain. Please, consider increasing your slippage tolerance from the [same clog icon from the borrow form] "Settings" menu."
