### ISSUE TITLE
Feature: Authentication

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#61]
**Todo**
- [x] User can login (w/ wallet)
- [x] User  can switch network
- [x] User can logout
- [x] integration of the auth component in the header
- [x] automatic reconnection

<img width="365" alt="image" src="https://user-images.githubusercontent.com/24778042/192242552-c24e2ae2-2765-46f1-9e3b-41dc164b1589.png">

https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=156%3A3847

**Comment by brozorec** [comment]
Drop off xState and we'll use React Context.

@doliG implements this, ETA 4 Oct

**Comment by doliG** [comment]
Note: after reading few article and discussed with chris we both agree that React.Context is not a good solution for our problem. We'll use a store then.

https://dayvster.com/blog/how-and-when-to-use-react-context
