### ISSUE TITLE
[Epic] Access Control and Roles

### ISSUE THREAD

**Issue by iafhurtado** [Fujicracy/fuji-v2#78]
The goal of this ticket is to have access controls and roles implemented in a consistent way across the whole system. This is a ticket to track progress.

**1. Chief**
- [x] `Owner`  ~~is a multisig that create, grants and revokes roles~~ see [comment](https://github.com/Fujicracy/fuji-v2/issues/78#issuecomment-1281580625)
- [x] ~~store all roles in a mapping:~~ `Treasury`, `Rebalancer`, `Liquidator`, `Harvester`, `Pauser`? and `AdminTimelock`?, see [comment](https://github.com/Fujicracy/fuji-v2/issues/78#issuecomment-1281580625)
- [ ] `createRole(role) onlyOwner`
- [x] `hasRole(role, address) returns (bool)` - check if the address has the specified role
- [x] `grantRole(role, address) onlyOwner` - give a role to the address
- [x] `revokeRole(role, address) onlyOwner` - revoke role of the address

**2. BorrowingVault and YieldVault**
- [x] implement `pause()` and `unpause()` with allowed callers or an address having the role `Pauser`
- [x] `setOracle()`, `setMaxLtv()` and `setLiqRatio()` can be called only by an address with `AdminTimelock` role
- [x] `liquidate()` can be called only by an address with `Liquidator` role
- [x] `setProviders()` can be called only by an address with `AdminTimelock` role
- [x] `setActiveProvider()` can be called only by an address with `Rebalancer` role (attention this can break existing tests)
- [x] `harvest()` - will be created after we deal with the topic "HarvestManager"

**3. FujiOracle**
- [x] `setPriceFeed()` -  can be called only by an address with `AdminTimelock` role

**4. AddrMapper - check the comments below**
- [x] create mapping `providerName => ( address1 => (address2 => IBT address))` - `providerName` has the format Name_Version or Name_Version_Asset (for ex. Aave_V2 but not Aave_v2, BeefyVelodrome_V6_sETHETH)
- [x] store all `providerName` in a array and add a getter function
- [x] setter function can be called by an address with `AdminTimelock` role

**Comment by DaigaroCota** [comment]
@brozorec , first awesome job on the detailing of the functions and the intended role. Some comments:

1. For `pause()` I am thinking we also add Externally Owned Accounts (yours or mine) for quick reaction. Or an alternative is that we create a "Security Multisg" including 1 signer from the auditors of the code. To also have them have some response responsibility. We can discuss the last point further. 
2. Excellent and completely agree in the need of  `pauseAllVaults()` and viceverse. Only question I will have, is if we introduce and array to iterate over? Or we keep track of all vaults off-chain?
3. I added Timelock to some of the functions that in the future I suggest should have this time component to allow people to react if they would like to react.  
4. For the `deployVault()` function in the `Chief`, in response to the comments, I would rather advocate to this be done by a future governance process instead of just "any EOA". The reason is that users could bloat our system with not relevant vaults, better to perhaps have a vetting process, because there is some risk associated with setting up the providers. Is not like Curve in where they are the lowest block and all risk lies within their code. 
5. For the `AddrMapper` you think perhaps we include a double nested mapping? 
For example:   (string) providerName => ( addressKey1 => (addressKey2 => IBT equivalent address))
I believe this way the mapper can be the same address and just keep adding maps.

**Comment by brozorec** [comment]
@iafhurtado @DaigaroCota fyi this ticket's description got updated with the needed details and an action plan.

**Comment by brozorec** [comment]
> For `pause()` I am thinking we also add Externally Owned Accounts (yours or mine) for quick reaction.

1. I suggest creating a `Pauser` role that can be attributed to EOAs.

> Excellent and completely agree in the need of pauseAllVaults() and viceverse. Only question I will have, is if we introduce and array to iterate over? Or we keep track of all vaults off-chain?

2. Yes, we keep them in an array in the contract.

4. I agree
5. I agree

6. Added specs in the ticket description.

@DaigaroCota

**Comment by iafhurtado** [comment]
Time estimation around 2 days

**Comment by brozorec** [comment]
1. and 2. very well
3. I started looking into it, very good ideas overall :+1: I have some feedback on the organization of the new code, I'll write it down directly in #94 
@DaigaroCota
